### ISSUE TITLE
Lastpass accelerator doesn't work

### ISSUE THREAD

**Issue by zendude213** [ajrosen/Alfred#10]
Hey ajrosen

Lastpass accelerator doesn't work.. after logging in and entering the command lpass.. I get nothing. 

I toggled debugging mode and tried again, and although it still didn't work (i.e. display my list of pws in the alfred prompt), it looks like the workflow succeeded in querying my pws under the hood (as I observed in the debug panel)

I downloaded and installed v3.31 workflow from Packal. Prior to that I installed it over CLI from the CLI command you provided on your github..this however only installed v1.0 which also didn't work and which is why i tried the 3.31 workflow

I also tried to put in my username as the value for lpuser in Workflow env variables for both 3.31 and 1.0... once again no dice

Finally I'm on Big Sur and the Alfred 4.5 beta

**Comment by ajrosen** [comment]
I haven't been able to reproduce this behavior.  I'm also using Alfred 4.5 (build 1248) on Monterey (public beta).

What version of the LastPass CLI do you have?  Does the debug panel show any errors?
