### ISSUE TITLE
clipboard timeout is empty

### ISSUE THREAD

**Issue by estiens** [ajrosen/Alfred#2]
<img width="267" alt="Screen Shot 2020-10-12 at 4 23 02 PM" src="https://user-images.githubusercontent.com/4022668/95791543-3567d100-0ca7-11eb-91a4-cd39e50a2b5c.png">

When trying to grab a password from lastpass, it shows a blank value for the clipboard timeout and it never actually shows up with the clipboard.

Tried with the default setting in the vars, and tried changing it to a higher or lower number

**Comment by estiens** [comment]
(I noted that field uses a TTL variable which doesn't seem to be set, however even if setting that, clipbord never receives anything for me)

**Comment by ajrosen** [comment]
At one point I renamed the variable from TTL to ClipboardTime.  Does the variable name in the workflow settings match the one used in the workflow itself?

<img width="532" alt="Screen Shot 2020-10-12 at 7 57 36 PM" src="https://user-images.githubusercontent.com/1565643/95800422-47586c80-0cc5-11eb-86af-a167d168ce75.png">
<img width="470" alt="Screen Shot 2020-10-12 at 7 58 09 PM" src="https://user-images.githubusercontent.com/1565643/95800433-4fb0a780-0cc5-11eb-88e8-4720b6d08314.png">

Or you can download version 1.0.2, which I've just uploaded to Packal and here.  It also fixes a small bug in the title of the failure notification.
