### ISSUE TITLE
can't get any items when inputting lpass

### ISSUE THREAD

**Issue by xuniaoji** [ajrosen/Alfred#6]
![image](https://user-images.githubusercontent.com/21085362/104082058-f299a300-526d-11eb-9beb-6a346a5ad1b8.png)

version: 2.1
already logged in

Could you help me figure out this? thanks!

**Comment by ajrosen** [comment]
I managed to reproduce this behavior, but I can't make it happen again.  I do have some questions..

- Is the workflow enabled
- Did you login from the terminal or the workflow
- Is the workflow's lpuser variable empty
- How did you get the LastPass and preference pane icons above the search field
