### ISSUE TITLE
lpass workflow may require exact match to the item name

### ISSUE THREAD

**Issue by qykong** [ajrosen/Alfred#7]
Hi, thanks for the super useful workflow. I noticed one thing when using it although I'm not sure if this is common. I usually have my password items saved with names being the full URLs which is auto-suggested by my lastpass plugin.  However, when I search for these items using this workflow, I have to type from the beginning to find the item. For example, if I have an item named "www.apple.com", typing "apple" won't find the item.

I looked into the workflow and found the "match" field will be exactly "www.apple.com" and seems in this case Alfred can't handle partial matching by ignoring the dots. So my quick workaround for this is to just in the awk script replacing dots with spaces and it worked fine. Hope this make sense 😄

**Comment by ajrosen** [comment]
I love great bug reports 😃 !

Instead of massaging fields to help Alfred's filtering, I'm now using awk to filter.  A nice benefit it was easy to filter on multiple fields.  Now you can match against an item's username and URL fields, as well as the path.

Thanks!
