### ISSUE TITLE
Restoring clipboard not working (incl. fix)

### ISSUE THREAD

**Issue by MarcThu** [ajrosen/Alfred#8]
After the delay and the check if the current clipboard-content is still the password, the clipboard is not set with the previous content. This is the first time, that I use Alfred Workflows, but I assume the variable "clip" (which the clipboard gets set after the delay) is not set. After adding a "get{clipboard}" (before the clipboard has changed the first time) and storing its content in the variable "clip" everything works now.

<img width="760" alt="Bildschirmfoto 2021-04-18 um 14 05 56" src="https://user-images.githubusercontent.com/45759034/115144991-ca30fa00-a04f-11eb-8ff4-d60c117c49d8.png">
<img width="827" alt="Bildschirmfoto 2021-04-18 um 14 11 08" src="https://user-images.githubusercontent.com/45759034/115145021-f0569a00-a04f-11eb-9dc7-34d47f2a2dc3.png">

**Comment by ajrosen** [comment]
I'd actually fixed this bug a while ago, but forgot to commit the changes.  It's now available as version 2.2.1.

Thanks!
